### ISSUE TITLE
Demo link 

### ISSUE THREAD

**Issue by vasanthudhaya** [gopavasanth/video-cut-tool#14]
Hi @gopavasanth, Need a demo link for the client side video cut-tool. That will be very useful for me.

**Comment by gopavasanth** [comment]
Front-end: https://tools.wmflabs.org/video-cut-tool-front-end/
Back-end: https://tools.wmflabs.org/video-cut-tool-back-end/

Learn how to use this tool: https://commons.wikimedia.org/wiki/File:Cropping_a_video_using_VideoCutTool.webm

Commons: https://commons.wikimedia.org/wiki/Commons:VideoCutTool

**Comment by vasanthudhaya** [comment]
Thanks @gopavasanth
